// <auto-generated />
using System;
using EurekaDb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EurekaDb.Migrations
{
    [DbContext(typeof(EurekaContext))]
    [Migration("20260322135337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("EurekaDb.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("LastOnline")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_online");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("TotalPlayTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_play_time");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("EurekaDb.Models.PlayerSession", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int?>("TimePlayedInSession")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_played_in_session");

                    b.HasKey("PlayerId", "Date");

                    b.ToTable("player_sessions", (string)null);
                });

            modelBuilder.Entity("EurekaDb.Models.PlayerSession", b =>
                {
                    b.HasOne("EurekaDb.Models.Player", "Player")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("PlayerId")
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("EurekaDb.Models.Player", b =>
                {
                    b.Navigation("PlayerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
